### ISSUE TITLE
LOAN ERROR! Never received UST for loan!!!!!

### ISSUE THREAD

**Issue by hr11111** [Anchor-Protocol/anchor-web-app#128]
Error ID: 165fe8e95de34310be300622eeb8d0b6

Hi,
Anchor  failed to provide me with the UST I borrowed, but my account says that I owe the money!? Please help.

**Comment by iamssen** [comment]
Your Borrow has been handled normally.

After the success of Tx, there was a Server Error in the process of querying the results to the API server, and the WebApp was not displayed normally.

Let me tell you how to check your Tx result. (I'd like to give you an easy link, but I can't write it down here because it's personal information.)

1. Look up your Terra Address in the search bar at <https://finder.terra.money>
2. Check the Transactions Section at the bottom for the Txhash starting with "5C58A..." (Currently it is the 5th). That is the result of your handling of Borrow.

We apologize for the inconvenience.
