### ISSUE TITLE
error trying to withdraw bETH

### ISSUE THREAD

**Issue by athenachu13** [Anchor-Protocol/anchor-web-app#385]
hi - discord is on lockdown. we can't send messages through telegram. so I'm going to try here -

I am trying to withdraw my collateral bETH but keep having "transaction failed" notices. 

The transaction requested has failed due to the following reason:

: Generic error: Price is too old: execute wasm contract failed

tx hash: [EA3198...838BEE](https://terrasco.pe/columbus-5/tx/EA319839DCE2E117FE3BE6215D8505411BFEAC9ECC629C9D89DD37F56A838BEE)

**Comment by jbrennin** [comment]
Same here

**Comment by jellicoe** [comment]
I did this yesterday and it worked and got my bETH out and back to Ethereum and convert to webETH  wormhole then cobert to stETH on lido

they might have stopped the Anchor eth Oracle because someone was manipulating it last night - look at this masssive bETH price spike over night (12 hours ago) it peaked to 303k per bETH also massive volume - locked bETH on anchor went from $33million to $6Million 

https://coinhall.org/charts/terra/terra1c0afrdc5253tkp5wt7rxhuj42xwyf2lcre0s7c

**Comment by kurrubuddu** [comment]
+1, please fix asap. Anchor team holding our assets hostages, much for decentralisation.

**Comment by athenachu13** [comment]
app.anchorprotocol.com is now down????!!! will it ever work? my ETH is stuck there, wht am I supposed to do? anyone has any success contacting the devs? I'm tried discord (currently shut down), tried Telegram (can't send messages in there), and tagged them on Twitter with my issue but no luck so far...what are we supposed to do?
